# This file instructs Redocly's linter to ignore the rules contained for specific parts of your API.
# See https://redocly.com/docs/cli/ for more information.
examples/spring-orders/openapi/paths/health.yaml:
  operation-4xx-response:
    - '#/get/responses'
