modules:
  - apps/demo-api
  - apps/demo-client
  - apps/demo-spring-client
  - libs/openapi-generator
  - libs/shared-amqp
  - libs/shared-common
  - libs/shared-i18n
  - libs/shared-kafka
  - libs/shared-ktor
  - libs/shared-mongo
  - libs/shared-redis
  - libs/shared-storage
  - plugins/openapi

plugins:
  - ./plugins/openapi
