type Permission @annotate(name: "Serializable", type: "serialization") {
    id: ID!
    name: String!
    description: String
    metadata: AuditMetadata!
}

type PermissionEvent @annotate(name: "Serializable", type: "serialization")  {
    id: ID!
    data: Permission
    type: EventType!
}

input CreatePermissionInput @annotate(name: "Serializable", type: "serialization") {
    name: String!
    description: String
}

input UpdatePermissionInput @annotate(name: "Serializable", type: "serialization") {
    name: String
    description: String
}

type Query {
    permissions: [Permission!]!
    permission(id: ID!): Permission!
}

type Mutation {
    createPermission(input: CreatePermissionInput!): Permission!
    updatePermission(id: ID!, input: UpdatePermissionInput!): Permission!
    deletePermission(id: ID!): Boolean!
}

type Subscription {
    permissionChanged: PermissionEvent!
}