package com.strange.spring.client

import kotlinx.serialization.json.Json
import org.springframework.core.convert.converter.ConverterRegistry
import org.springframework.format.support.DefaultFormattingConversionService
import org.springframework.http.HttpHeaders
import org.springframework.http.codec.json.KotlinSerializationJsonDecoder
import org.springframework.http.codec.json.KotlinSerializationJsonEncoder
import org.springframework.web.reactive.function.client.ExchangeFilterFunction
import org.springframework.web.reactive.function.client.WebClient
import org.springframework.web.service.invoker.HttpRequestValues
import org.springframework.web.service.invoker.HttpServiceProxyFactory

/**
 * [httpServiceFactory] with the four settings an interface generated by `plugins/openapi` needs.
 *
 * **None of the four fails at build time when left out**, which is the reason they are gathered here
 * rather than written out per application. Each one is a silent wrong answer:
 *
 * | Left out | What happens |
 * | --- | --- |
 * | [json] | a generated model whose field is a `kotlin.time.Instant` is handed to Jackson, which has never heard of the type |
 * | [enums] | Spring writes an enum argument with `Enum.name()` and never consults `toString()`, so a document spelling a value in kebab-case goes out as the Kotlin name — a request that succeeds and matches nothing |
 * | [operations] | by the time a `ClientRequest` exists the method is gone, so a generated filter cannot tell which operation it is looking at: the error filter falls back to the untyped exception and an auth filter attaches nothing |
 * | the error filter, in [filters] | a documented non-2xx arrives as the untyped `ApiException` rather than the generated exception carrying a parsed body |
 *
 * The arguments are the *generated* symbols, passed rather than named, because the generator emits
 * them into each module's own `<packageName>.utils`: same shapes, different classes. Their Spring
 * types are the same everywhere, which is what lets this function be written once.
 *
 * ```kotlin
 * val factory = generatedApiFactory(
 *     baseUrl,
 *     json = stxWebJson,                          // only with `models: Kotlinx`
 *     enums = ::registerApiEnumConverters,
 *     operations = apiOperationProcessor(),
 *     filters = listOf(apiAuthFilter(credentials), apiErrorFilter()),
 * )
 * val orders = factory.withClient<IOrdersService>()
 * val health = factory.withClient<IHealthService>()
 * ```
 *
 * **One factory, a client per interface.** Building one per interface rebuilds the `WebClient`
 * underneath it, and the second interface is where one of these settings quietly goes missing.
 *
 * [headers] runs per request — `{ it.setBearerAuth(token) }` — which is where an API with
 * authentication and no generated auth filter puts its token. [filters] are added in the order
 * given, and all of them run closer to the transport than [httpServiceFactory]'s own status handler,
 * which is what lets a generated error filter answer before the untyped fallback does.
 */
@Suppress("LongParameterList")
fun generatedApiFactory(
    baseUrl: String,
    json: Json? = null,
    enums: ((ConverterRegistry) -> Unit)? = null,
    operations: HttpRequestValues.Processor? = null,
    filters: List<ExchangeFilterFunction> = emptyList(),
    headers: (HttpHeaders) -> Unit = {},
    factory: HttpServiceProxyFactory.Builder.() -> Unit = {},
    configure: WebClient.Builder.() -> Unit = {},
): HttpServiceProxyFactory =
    httpServiceFactory(
        baseUrl,
        headers,
        factory = {
            enums?.let { conversionService(DefaultFormattingConversionService().also(it)) }
            operations?.let { httpRequestValuesProcessor(it) }
            // Last, so a caller can still override anything set above.
            factory()
        },
        configure = {
            json?.let { codecs(it) }
            filters.forEach(::filter)
            configure()
        },
    )

/**
 * kotlinx-serialization on both sides of the exchange, from the application's own `Json`.
 *
 * `models: Kotlinx` generates `@Serializable` classes, and `stx.json.enabled` puts the same codecs on
 * the server — so passing the application's `stxWebJson` bean is what makes a client read exactly
 * what the server wrote, down to the `Instant` format.
 */
private fun WebClient.Builder.codecs(json: Json) =
    codecs {
        it.defaultCodecs().kotlinSerializationJsonDecoder(KotlinSerializationJsonDecoder(json))
        it.defaultCodecs().kotlinSerializationJsonEncoder(KotlinSerializationJsonEncoder(json))
    }
