package com.strange.jpa.query

import jakarta.persistence.criteria.CommonAbstractCriteria
import jakarta.persistence.criteria.CriteriaDelete
import jakarta.persistence.criteria.CriteriaQuery
import jakarta.persistence.criteria.CriteriaUpdate
import org.hibernate.query.criteria.HibernateCriteriaBuilder
import org.hibernate.query.criteria.JpaCriteriaInsert
import org.hibernate.query.sqm.tree.SqmVisitableNode
import org.hibernate.reactive.stage.Stage

/**
 * Hibernate's own criteria builder, for a query written against the Criteria API directly.
 *
 * ```kotlin
 * val criteria = session.criteria.createQuery(Book::class.java)
 * val author = criteria.from(Author::class.java)
 * val books = author.join<Author, Book>("books")
 * criteria.where(author.get<String>("name").`in`("Neal Stephenson", "William Gibson"))
 * criteria.select(books)
 *
 * session.query(criteria).list()
 * ```
 *
 * Not named `criteriaBuilder`, because `Stage.QueryProducer` already has a member spelled that way
 * and a member always beats an extension. It declares the JPA interface, which has no `sql()`, no
 * `ilike` and none of the window functions — while handing back the session factory's own
 * [HibernateCriteriaBuilder], which has all three. This is that same object, said out loud.
 *
 * **There is no static metamodel here, and there cannot be.** `Book_.title` is generated by
 * `hibernate-jpamodelgen`, a *javac* annotation processor; this toolchain runs Java annotation
 * processing for Java and Android modules only, has no kapt, and jpamodelgen has no KSP build. So a
 * criteria written this way names its attributes with strings, unchecked until the query runs —
 * which is the whole reason `com.strange.jpa.dsl` exists and writes them as `Book::title` instead.
 * Reach for this where the DSL does not go: subqueries, set operations, window functions,
 * `insert … select`.
 */
val Stage.QueryProducer.criteria: HibernateCriteriaBuilder
    get() = criteriaBuilder as HibernateCriteriaBuilder

/**
 * A criteria query, run through this module's terminals.
 *
 * The bridge back: a query built by hand gets the same suspending `list`, `first`, `single`,
 * `singleOrNull` and `count` an HQL one has, instead of a `CompletionStage` the caller has to
 * remember to await.
 */
fun <R> Stage.QueryProducer.query(criteria: CriteriaQuery<R>): JpaQuery<R> = JpaQuery({ criteria.hql() }, createQuery(criteria))

/** A criteria `update`, run through this module's terminals. */
fun Stage.QueryProducer.mutate(criteria: CriteriaUpdate<*>): JpaMutation = JpaMutation(createMutationQuery(criteria))

/** A criteria `delete`, the same way. */
fun Stage.QueryProducer.mutate(criteria: CriteriaDelete<*>): JpaMutation = JpaMutation(createMutationQuery(criteria))

/**
 * A criteria `insert`, the same way — `insert … select`, or `insert … values`.
 *
 * Hibernate's, not JPA's: [JpaCriteriaInsert] comes off [criteria] as `createCriteriaInsertSelect`
 * or `createCriteriaInsertValues`, and there is no JPA equivalent to widen it to. It is also the one
 * statement `com.strange.jpa.dsl` has no spelling for at all.
 */
fun Stage.QueryProducer.mutate(criteria: JpaCriteriaInsert<*>): JpaMutation = JpaMutation(createMutationQuery(criteria))

/**
 * The criteria rendered back to HQL, for an exception that has to say which query it was.
 *
 * A criteria has no source text, so this walks the tree Hibernate built and prints it. It runs only
 * when a terminal is about to throw.
 */
internal fun CommonAbstractCriteria.hql(): String =
    runCatching {
        (this as SqmVisitableNode).toHqlString()
    }.getOrElse { "a criteria query" }
