package com.strange.jpa.query

import jakarta.persistence.criteria.CommonAbstractCriteria
import jakarta.persistence.criteria.CriteriaDelete
import jakarta.persistence.criteria.CriteriaQuery
import jakarta.persistence.criteria.CriteriaUpdate
import org.hibernate.query.criteria.HibernateCriteriaBuilder
import org.hibernate.query.criteria.JpaCriteriaInsert
import org.hibernate.query.sqm.tree.SqmVisitableNode
import org.hibernate.reactive.stage.Stage

/**
 * Hibernate's own criteria builder, for a query written against the Criteria API directly.
 *
 * ```kotlin
 * val criteria = session.createQuery<Book>()
 * val author = criteria.from(Author::class.java)
 * val books = author.joinEach(Author::books)
 * criteria.where(author[Author::name] oneOf listOf("Neal Stephenson", "William Gibson"))
 * criteria.select(books)
 *
 * session.query(criteria).list()
 * ```
 *
 * Not named `criteriaBuilder`, because `Stage.QueryProducer` already has a member spelled that way
 * and a member always beats an extension. It declares the JPA interface, which has no `sql()`, no
 * `ilike` and none of the window functions — while handing back the session factory's own
 * [HibernateCriteriaBuilder], which has all three. This is that same object, said out loud.
 *
 * **There is no static metamodel here, and there cannot be.** `Book_.title` is generated by
 * `hibernate-jpamodelgen`, a *javac* annotation processor; this toolchain runs Java annotation
 * processing for Java and Android modules only, has no kapt, and jpamodelgen has no KSP build. So a
 * criteria written against the bare API names its attributes with strings, unchecked until the query
 * runs. `com.strange.jpa.criteria` is the answer to that and nothing more: extensions on Criteria's
 * own types that take `Book::title` where a generated `Book_` would have been, and leave the shape
 * of a criteria exactly as JPA defines it.
 */
val Stage.QueryProducer.criteria: HibernateCriteriaBuilder
    get() = criteriaBuilder as HibernateCriteriaBuilder

/**
 * A criteria query, run through this module's terminals.
 *
 * The bridge back: a query built by hand gets the same suspending `list`, `first`, `single`,
 * `singleOrNull` and `count` an HQL one has, instead of a `CompletionStage` the caller has to
 * remember to await.
 */
fun <R> Stage.QueryProducer.query(criteria: CriteriaQuery<R>): JpaQuery<R> = JpaQuery({ criteria.hql() }, createQuery(criteria))

/** A criteria `update`, run through this module's terminals. */
fun Stage.QueryProducer.mutate(criteria: CriteriaUpdate<*>): JpaMutation = JpaMutation(createMutationQuery(criteria))

/** A criteria `delete`, the same way. */
fun Stage.QueryProducer.mutate(criteria: CriteriaDelete<*>): JpaMutation = JpaMutation(createMutationQuery(criteria))

/**
 * A criteria `insert`, the same way — `insert … select`, or `insert … values`.
 *
 * Hibernate's, not JPA's: [JpaCriteriaInsert] comes off [criteria] as `createCriteriaInsertSelect`
 * or `createCriteriaInsertValues`, and there is no JPA equivalent to widen it to.
 * `com.strange.jpa.criteria.createInsert` and `createInsertSelect` are the reified spellings.
 */
fun Stage.QueryProducer.mutate(criteria: JpaCriteriaInsert<*>): JpaMutation = JpaMutation(createMutationQuery(criteria))

/**
 * The criteria rendered back to HQL, for an exception that has to say which query it was.
 *
 * A criteria has no source text, so this walks the tree Hibernate built and prints it. It runs only
 * when a terminal is about to throw.
 */
internal fun CommonAbstractCriteria.hql(): String =
    runCatching {
        (this as SqmVisitableNode).toHqlString()
    }.getOrElse { "a criteria query" }

/**
 * The same builder, off the factory — for a criteria assembled without opening a session.
 *
 * `Stage.SessionFactory` declares it as [HibernateCriteriaBuilder] already, so this is a name rather
 * than a cast: `factory.criteria` and `session.criteria` read alike, and the statement built from
 * either is the same value.
 */
val Stage.SessionFactory.criteria: HibernateCriteriaBuilder
    get() = criteriaBuilder
